spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    # ADICIONE A LINHA ABAIXO
    defer-datasource-initialization: true
    show-sql: true

# ADICIONADO: Propriedades para JWT
app:
  jwtSecret: SpringBootSecretKeyForJWTsMustBeLongerThan256Bits
  jwtExpirationInMs: 86400000